{ pkgs, ... }:
{
  home.packages = with pkgs; [
    blockbench
    btop
    cmake
    fastfetch
    feishin
    flameshot
    hyfetch
    jq
    kdePackages.ark
    kdePackages.dolphin
    kdePackages.gwenview
    kdePackages.kate
    kdePackages.kio
    kdePackages.kio-admin
    kdePackages.kio-extras
    kdePackages.kio-fuse
    krita
    libreoffice-qt6-fresh
    lxqt.pavucontrol-qt
    mpv
    obs-studio
    prismlauncher
    vesktop
    vlc
    wl-clipboard
  ];
}
