# Reload config
bind=SUPER,r,reload_config

# Applications
bind=SUPER,space,spawn,wofi
bind=SUPER+SHIFT,space,spawn,waypaper
bind=SUPER,q,spawn,konsole
bind=SUPER,f,spawn,zen-twilight
bind=SUPER,e,spawn,dolphin
bind=SUPER+SHIFT,s,spawn,flameshot gui

# Close window
bind=SUPER,c,killclient,

# Switch window focus
bind=SUPER,Tab,focusstack,next
bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,Up,focusdir,up
bind=ALT,Down,focusdir,down

# Swap window
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# Switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=SUPER,v,togglefloating,
bind=SUPER,h,togglefullscreen,
bind=SUPER+SHIFT,h,togglefakefullscreen,

# Switch between workspaces
bind=SUPER,1,view,1,0
bind=SUPER,2,view,2,0
bind=SUPER,3,view,3,0
bind=SUPER,4,view,4,0
bind=SUPER,5,view,5,0
bind=SUPER,6,view,6,0
bind=SUPER,7,view,7,0
bind=SUPER,8,view,8,0
bind=SUPER,9,view,9,0
axisbind=SUPER,UP,viewtoleft,0
axisbind=SUPER,DOWN,viewtoright,0

# Move windows between workspaces
bind=SUPER+SHIFT,1,tag,1,0
bind=SUPER+SHIFT,2,tag,2,0
bind=SUPER+SHIFT,3,tag,3,0
bind=SUPER+SHIFT,4,tag,4,0
bind=SUPER+SHIFT,5,tag,5,0
bind=SUPER+SHIFT,6,tag,6,0
bind=SUPER+SHIFT,7,tag,7,0
bind=SUPER+SHIFT,8,tag,8,0
bind=SUPER+SHIFT,9,tag,9,0

# Move windows with mouse
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Exit Mango
bind=SUPER,m,quit
