layerrule=animation_type_open:slide,layer_name:wofi
layerrule=animation_type_close:slide,layer_name:wofi

layerrule=animation_type_open:slide,layer_name:dunst
layerrule=animation_type_close:slide,layer_name:dunst

windowrule=animation_type_open:slide,animation_type_close:slide,isfloating:1,appid:waypaper
windowrule=animation_type_open:slide,animation_type_close:slide,isfloating:1,title:flameshot

windowrule=force_tearing:1,title:Counter-Strike 2
