source=~/.config/mango/appearance.conf
source=~/.config/mango/autorun.conf
source=~/.config/mango/binds.conf
source=~/.config/mango/input.conf
source=~/.config/mango/misc.conf
source=~/.config/mango/monitors.conf
source=~/.config/mango/variables.conf
source=~/.config/mango/window-layer-rules.conf
source=~/.config/mango/workspaces.conf
